[package]
name = "xtask"
publish = false
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = {version = "0.3", default-features = false }
anyhow = "1"

[package.metadata.release]
release = false
