[package]
name = "aya-log-common"
version = "0.1.1"
edition = "2018"

[features]
default = []
userspace = [ "aya" ]

[dependencies]
aya = { version = "0.10.5", optional=true }

[lib]
path = "src/lib.rs"
